# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET and Deploy to Vercel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish .NET project
      run: dotnet publish -c Release -o ./publish

    - name: Install Vercel CLI
      run: npm install -g vercel@latest

    - name: Deploy to Vercel
      run: vercel ./publish --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --name blazor-wasm-phayarsar
      env:
        VERCEL_TELEMETRY_DISABLED: 1
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
